name: GitHub Pages Release action
description: Release GitHub Pages
author: Shunsuke Suzuki
branding:
  icon: git-commit
  color: blue
inputs:
  github_token:
    description: |
      GitHub Access Token
      contents:write - Push commits
    required: false
  app_id:
    description: |
      GitHub App ID
    required: false
  app_private_key:
    description: |
      GitHub App Private Key
    required: false
  publish_branch:
    description: 'Set a target branch for deployment.'
    required: false
    default: gh-pages
  publish_dir:
    description: 'Set an input directory for deployment.'
    required: false
    default: 'public'
  destination_dir:
    description: 'Set an destination subdirectory for deployment.'
    required: false
    default: ''
  external_repository:
    description: 'Set an external repository (owner/repo).'
    required: false
  cname:
    description: 'Set custom domain'
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      id: repo_name
      run: |
        repo=${REPOSITORY:-$GITHUB_REPOSITORY}
        echo "value=${repo#*/}" >> "$GITHUB_OUTPUT"
        echo "full_name=$repo" >> "$GITHUB_OUTPUT"
      env:
        REPOSITORY: ${{ inputs.external_repository }}

    - shell: bash
      id: dir
      run: echo "value=.gh-pages-action-$GITHUB_RUN_ID" >> "$GITHUB_OUTPUT"

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: ${{ inputs.external_repository }}
        ref: ${{ inputs.publish_branch }}
        persist-credentials: false
        path: ${{ steps.dir.outputs.value }}
        sparse-checkout: |
          ${{ inputs.destination_dir }}

    - shell: bash
      env:
        SOURCE: ${{ inputs.publish_dir }}
        DEST: ${{ inputs.destination_dir }}
        DIR: ${{ steps.dir.outputs.value }}
        CNAME: ${{ inputs.cname }}
      run: |
        rm -Rf "$DIR/$DEST"
        cp -R "$SOURCE" "$DIR/$DEST"
        cd "$DIR"

        touch "${DEST:-.}/.nojekyll"

        if [ -n "$CNAME" ]; then
          echo "$CNAME" > "$DEST/CNAME"
        fi

    # Commit changes
    - uses: suzuki-shunsuke/commit-action@eba143cd31bc6b7f7844c4a2672ad321e91061f1 # v0.0.9
      with:
        github_token: ${{ inputs.github_token }}
        app_id: ${{ inputs.app_id }}
        app_private_key: ${{ inputs.app_private_key }}
        repository: ${{ inputs.external_repository }}
        branch: ${{ inputs.publish_branch }}
        commit_message: |
          deploy: ${{ github.repository }}@${{ github.sha }}
          ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

    - shell: bash
      env:
        DIR: ${{ steps.dir.outputs.value }}
      run: |
        rm -Rf "$DIR"
